name: Test Self Hosted Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Runner
        run: |
          echo "Runner is working!"
          hostname
          whoami
          pwd
          uname -a
